version: 2.1
orbs:
  node: circleci/node@1.1.6
publish: &publish
  name: Publish to Dev
  command: |
    if [[ "$CIRCLE_BRANCH" = "master" ]] && [[ -z "$CIRCLE_PULL_REQUEST" ]]
    then
      DEV_TO_GIT_TOKEN=$DEV_TO_GIT_TOKEN yarn run dev-to-git
    fi
jobs:
  dev-to-git:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn run prettier:check
            - run: yarn run embedme:check
            - run:
                <<: *publish
workflows:
  dev-to-git:
    jobs:
      - dev-to-git
